coverage:
  acceptable: 60%
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 1min
  badge:
    path: docs/time.svg
diff:
  if: github.event_name == 'pull_request'
  path: .octocov/report.json
push:
  if: env.GITHUB_REF == 'refs/heads/main'
comment:
  if: github.event_name == 'pull_request'
  enable: true
report:
  if: env.GITHUB_REF == 'refs/heads/main'
  path: .octocov/report.json
