coverage:
  acceptable: current >= 60%
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 1min30sec
  badge:
    path: docs/time.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
