coverage:
  acceptable: 60%
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 1min
  badge:
    path: docs/time.svg
diff:
  datastores:
    - local://.octocov
push:
  enable: true
  if: env.GITHUB_REF == 'refs/heads/main'
comment:
  enable: true
report:
  if: env.GITHUB_REF == 'refs/heads/main'
  datastores:
    - github://k1LoW/octocov/.octocov
