coverage:
  acceptable: current >= 60% && diff >= 0.5%
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 1min30sec
  badge:
    path: docs/time.svg
diff:
  if: github.event_name == 'pull_request'
  path: .octocov/report.json
push:
  if: is_default_branch
comment:
  if: github.event_name == 'pull_request'
report:
  if: is_default_branch
  path: .octocov/report.json
