name: build

on: push

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.16]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci

      - name: Run lint
        uses: golangci/golangci-lint-action@v2

      - name: Run octocov-action
        uses: k1LoW/octocov-action@v0

      - name: Run build octocov
        run: make coverage

      - name: Commit badge and example
        uses: EndBug/add-and-commit@v7
        if: github.ref == 'refs/heads/main'
        with:
          add: 'docs/coverage.svg docs/ratio.svg docs/time.svg example/**'
