name: parallel

on: workflow_dispatch

jobs:
  job-parallel:
    name: parallel tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
        parallel: [0,1,2]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEBUG: 1
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run tests ${{ matrix.parallel }}
        run: make ci

      - name: Run build octocov
        run: |
          make build
          ./octocov --dump --config testdata/octocov_parallel_tests.yml
