name: tagpr
on:
  push:
    branches:
      - main

jobs:
  # tagpr:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: Check out source code
  #       uses: actions/checkout@v3

  #     - id: run-tagpr
  #       name: Run tagpr
  #       uses: Songmu/tagpr@v1

  release-darwin:
    name: Release assets for maoOS
    # needs: tagpr
    # if: needs.tagpr.outputs.tagpr-tag != ''
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        run: |
          brew uninstall go@1.17
          brew install go
          brew install goreleaser

      - name: Release
        run: |
          goreleaser --config .goreleaser/darwin.yml --rm-dist
          
  release-linux:
    name: Release assets for Linux
    # needs: tagpr
    # if: needs.tagpr.outputs.tagpr-tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --config .goreleaser/linux.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
